### PR TITLE
removed phantomjs dependency

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
Addresses https://github.com/hammerlab/pileup.js/issues/517 and https://github.com/hammerlab/pileup.js/issues/503

**Comment by akmorrow13** [comment]
TODOs:

- [ ] Test with node 12.0.0

- [ ] fix coverage

**Comment by akmorrow13** [comment]
ping @piotr-gawron maybe this will fix issue https://github.com/hammerlab/pileup.js/issues/517

**Comment by piotr-gawron** [comment]
Dear @akmorrow13,
I checked it and it works fine: everything installed without problem and all tests are green (checked on both 12.0.0 and 10.15.3).
 
Since you decided to remove deprecated phantomejs do you also plan to upgrade other libraries? simple 
```
npm audit
```
reports `found 42 vulnerabilities (9 low, 22 moderate, 10 high, 1 critical)` in the dependencies...

**Comment by akmorrow13** [comment]
Thanks for testing @piotr-gawron! Removing and replacing some of these libraries broke different aspects of pileup.js, so I will not be addressing them here. PRs for fixes are always welcome, however!

**Pull request merged**
