### PR TITLE
Remove whitespace from reference on zoom out

### LINKED ISSUE #274: Reference track color blocks shouldn't have whitespace when zoomed out
It creates a sort of scintillating effect; would look a little less busy if the block of color were solid.

### PR DESCRIPTION
**Pull request by danvk**
Fixes #274 

This revives a change from @ihodes 

The new whitespace behavior is good. I'm not sure what I think about these new colors, though. The yellow is a bit hard to seen against white & gray backgrounds. @ihodes @armish what do you guys think?

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/344)

### CODE REVIEW

**Comment by danvk** [comment]
(strongly recommend running `git webdiff https://github.com/hammerlab/pileup.js/pull/344` to look at the screenshot changes—it's hard to see what's going on in the GitHub UI.)

**Comment by ihodes** [comment]
Agreed wrt the yellow being more difficult to see.

**Comment by danvk** [comment]
I reverted the color changes. What do you think now @ihodes?

**Comment by ihodes** [comment]
LGTM! hope to find some better colors sometime.

**Pull request merged**
