### PR TITLE
Migrate Coverage from SVG→canvas

### PR DESCRIPTION
**Pull request by armish**
Rendering with canvas:
screen recording 2015-09-24 at 10 47 pm

See #255 

The labels used to be much sharper and they look uglier on the canvas, but hopefully #261 will solve this issue once and for all.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/266)

### CODE REVIEW

**Comment by danvk** [comment]
Looks great, thanks for doing this!

---

Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[src/main/CoverageTrack.js, line 60 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1R5WtSRMYOR1Hl473)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L60)):</sup>
Is the `<div>` necessary? Can this just be

```
return <canvas ref='canvas' />;
```

---

<sup>**[src/main/CoverageTrack.js, line 123 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1S0AxdNLwtBwpuj7A)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L123)):</sup>
This can be a constant, not a function.

---

<sup>**[src/main/CoverageTrack.js, line 132 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1ReUvBN-DbQnZaO71)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L132)):</sup>
Pull this outside the `forEach`.

---

<sup>**[src/main/CoverageTrack.js, line 133 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1S7w-YYbX8bjW03HU)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L133)):</sup>
just my 2¢, but I think this would be clearer & more concise if you killed the functions and inlined the computation, e.g.

```javascript
var barWidth = xScale(1) - xScale(0),
    x = xScale(bin.x),
    ...
```

---

<sup>**[src/main/CoverageTrack.js, line 140 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1RXYAeIvi_dmGZiuY)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L140)):</sup>
`ctx.restore()` calls should be balanced with `ctx.save()` calls. I don't see any `save` calls, so I think you can kill this?

---

<sup>**[src/main/CoverageTrack.js, line 158 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1SbXZ1iOVVUJOie-X)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L158)):</sup>
You don't `stroke` anything, so this can be removed.

---

<sup>**[src/main/CoverageTrack.js, line 167 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1Sgj6t4qca7qC-Drm)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L167)):</sup>
(same comment about `restore`)

---

<sup>**[src/main/style.js, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1TC1tr3JRVD2gbB9R)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/style.js#L37)):</sup>
You never use this.

---

<sup>**[src/main/style.js, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1TFRY0MxHANkqyyBt)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/style.js#L38)):</sup>
Does `Helvetica Neue` need to be in quotes? If not, switch to `''`-style quoting and change the other font strings in this file, too.

---

<sup>**[src/test/CoverageTrack-test.js, line 93 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1Te-ys9_34loGnE_S)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/test/CoverageTrack-test.js#L93)):</sup>
I'd prefer to test this through the `fillText` calls, rather than the data objects. That way you're really testing that this label gets put on the screen.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/266)

**Comment by armish** [comment]
thanks for the review, Dan! Addressed all of your comments.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/main/CoverageTrack.js, line 60 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1R5WtSRMYOR1Hl473)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L60)):</sup>
I thought it was necessary, but I was wrong. Removed that `div` wrapper.

---

<sup>**[src/main/CoverageTrack.js, line 133 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1S7w-YYbX8bjW03HU)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L133)):</sup>
I will take that 2¢ ;)

---

<sup>**[src/main/CoverageTrack.js, line 140 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1RXYAeIvi_dmGZiuY)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/CoverageTrack.js#L140)):</sup>
I guess I was confused about their utility -- thanks for the explanation. I removed the repetitive calls.

---

<sup>**[src/main/style.js, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1TFRY0MxHANkqyyBt)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/style.js#L38)):</sup>
turns out you do need those quotes. So I added them back in and also changed the `LOOSE_TEXT_STYLE` to match with that.

---

<sup>**[src/test/CoverageTrack-test.js, line 93 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1Te-ys9_34loGnE_S)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/test/CoverageTrack-test.js#L93)):</sup>
done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/266)

**Comment by danvk** [comment]
Looks good, just one more comment.

---

Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/main/CoverageTrack.js, line 133 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-4Wid-ONQ65gCrHNXX)** ([raw file](https://github.com/hammerlab/pileup.js/blob/dff2a24a25a9077393034478035f4f227e313be2/src/main/CoverageTrack.js#L133)):</sup>
you can hoist this constant out, too.

---

<sup>**[src/main/style.js, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1TFRY0MxHANkqyyBt)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/style.js#L38)):</sup>
I wonder if that fixes #265?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/266)

**Comment by armish** [comment]
done! 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/main/CoverageTrack.js, line 133 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-4Wid-ONQ65gCrHNXX)** ([raw file](https://github.com/hammerlab/pileup.js/blob/dff2a24a25a9077393034478035f4f227e313be2/src/main/CoverageTrack.js#L133)):</sup>
yeah, good catch.

---

<sup>**[src/main/style.js, line 37 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/266#-K-1TFRY0MxHANkqyyBt)** ([raw file](https://github.com/hammerlab/pileup.js/blob/643422d6fc39f84e39073016fc19ecd894e2b6d3/src/main/style.js#L37)):</sup>
looks like not :(

Imgur

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/266)

**Comment by danvk** [comment]
:+1: :shipit:

**Pull request merged**
