### PR TITLE
Show progress while loading pileups

### LINKED ISSUE #170: Add track loading indication
For example, BAMs can take a while to render; would be good to see that something is happening.

### PR DESCRIPTION
**Pull request by danvk**
Not especially pretty, but it works!

screen recording 2015-06-17 at 02 32 pm

Fixes #170

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/197)

### CODE REVIEW

**Comment by danvk** [comment]
cc @jaclynperrone for ugly loading indicator :)

**Comment by armish** [comment]
the code looks good to me; leaving the design review to @jaclynperrone ;)

**Comment by jaclynperrone** [comment]
:fire: Lookin hot! :fire: 

It may benefit from some Helvetica, a lighter border and some padding. But only if you are feeling fancy today.

**Comment by danvk** [comment]
I'm going to merge this in—will tweak the styles in a follow-up.

**Pull request merged**
