### PR TITLE
Support for BioJS framework, better demoing and require-able package

### LINKED ISSUE #113: Post a public demo
This is pretty essential in evaluating a library!

### LINKED ISSUE #166: Publish pileup.js as a BioJS component
[BioJS](http://biojs.net/) has been gaining quite a lot of attraction from the Bioinformatics community lately and a majority of the early adaptors gained a considerable user base due to this increased visibility.  I think it makes sense to start supporting the framework as it is really not too much of a work. 

This is loosely related to issues #136 and #113; and once done, we can think about adding a short write-up to this F1000 collection to make it even more public: http://f1000research.com/articles/3-56/v1

### PR DESCRIPTION
**Pull request by armish**
- BioJS: added relevant keywords and forced `browserify` to properly expose a require-able `pileup` (fixes #166 and #136)
- With BioJS's `sniper` support, we now have a better demo mechanism and this will allow us to demo the package on BioJS repository in an automated manner (see examples on [http://biojs.net/](http://biojs.net/) -- resolves #113)
- README now features a screenshot of the demo

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/169)

### CODE REVIEW

**Comment by danvk** [comment]
Thanks for these changes! Aside from a few nits and questions, the only substantive issue is whether it makes more sense to fork the demo or migrate it to BioJS entirely.

(I did this review using Reviewable, which I generally prefer for larger code reviews. See these [Lunch and Learn slides][2] for more background on why.)

One other note: here are some [best practices][1] for commit messages. Highlights are that the first line of a commit message should generally be a short (~50 char) description of the commit written in imperative voice, then a blank line followed by more descriptive text (if necessary). If the commit description is a list of unrelated changes, then the commit should probably be split :) No need to change your commits in this PR, just something to keep in mind in the future.

Sorry to nit-pick, but it's good to get on the same page about style issues at the start of working together! Let me know if you have any questions, either about the feedback or about using Reviewable.

[1]: https://github.com/erlang/otp/wiki/Writing-good-commit-messages
[2]: https://docs.google.com/presentation/d/1wHE5OUXHZTnTXlb8eJJvxMrDkSqD2y8ixkJLNPVZykU/edit#slide=id.g5dac6d992_2_28

---

Review status: 0 of 7 files reviewed, 8 unresolved discussions, all commit checks successful.

---

<sup>**[examples/playground.js, line 34 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ1qGVtJPvAJWiSI7z)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/examples/playground.js#L34)):</sup>
nit: we generally follow the Google JS Style guide, which says [no space after `{` and before `}`][style]

[style]: https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Code_formatting#Code_formatting

---

<sup>**[Gruntfile.js, line 39 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ-Nk3SBVaxhnj5jiO)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/Gruntfile.js#L39)):</sup>
Can you say a little more about what this does, i.e. how it fixes #136 

---

<sup>**[Gruntfile.js, line 39 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ1yhbRgupzmfl-9nP)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/Gruntfile.js#L39)):</sup>
same nit about `[ foo ]` vs `[foo]`.

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ-_zH1sB-cMSpu_hJ)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L13)):</sup>
It's great to support BioJS, but I don't want to create the impression that we depend on it. For someone coming to the tool who's unfamiliar with BioJS (like myself), seeing a simple demo with entirely familiar components (i.e. HTML and JS) is helpful.

What do you think about forking `playground.html` into a plain-HTML version and a BioJS version?

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0oBjv1bSbIqvkE0J)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L13)):</sup>
I generally prefer out-of-line (`[BioJS sniper][sniper]`) to inline (`[BioJS sniper](url)`) for links, since they don't break the flow of the text.

---

<sup>**[README.md, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0J9iRoja7M_9HK9s)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L19)):</sup>
Does the `sniper` server support [http range requests][1]? If not, this will break local development.

[1]: http://en.wikipedia.org/wiki/Byte_serving

---

<sup>**[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0WhLzQo-b7imqHIo)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L23)):</sup>
I'm guessing this means you got it running successfully :)

---

<sup>**[src/pileup.js, line 79 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0bmhGfXQZOFXRo_z)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/src/pileup.js#L79)):</sup>
I think you can revert changes to this file? It doesn't look like any of them would have an effect.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
No worries about nit-picking -- this is amazingly useful for me, so thanks for taking the time to write this review, Dan. Also thanks for pointing the best practices document/slides, let me digest these and do not make the same mistakes again ;)

Re: forking the demo and migrating it to BioJS -- although I like BioJS quite a lot, I still think depending solely on them for the demo might be risky (as they sometimes go down or become unstable). For branding purposes, it would be great to host a more informative demo on hammerlab.org, but  this is just a thought. I am open to go with the option you think is the best.

---

Review status: 0 of 7 files reviewed, 8 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 7 files reviewed, 7 unresolved discussions, some commit checks failed.

---

<sup>**[Gruntfile.js, line 39 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ-Nk3SBVaxhnj5jiO)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/Gruntfile.js#L39)):</sup>
When you don't have this, the browserfied JS file does not define `require`, but simply wraps everything in an anonymous function for scoping. What this line does is to tell the browserify plugin that we are going to ask for the `pileup` module (which is defined in `./src/pileup.js` and to create a require object to expose this functionality.

I actually didn't know about this and when I realized that the aggregated file does not have a require, a few Google searches have led me to this:
http://stackoverflow.com/questions/25585903/browserify-external-requires-with-grunt-browserify

and I simply implemented the solution mentioned there in a cleaner way.

I think the reason you were getting those realm of errors in Cycledash was simply because `pileup` was not exposed through a `require` function earlier.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ-_zH1sB-cMSpu_hJ)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L13)):</sup>
That's a good idea -- I will include the JS file from a plain-HTML version as an alternative. This way we don't have to maintain two different demos.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0J9iRoja7M_9HK9s)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L19)):</sup>
I didn't have any problems when I was playing with it. It looks like it does support range requests.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 23 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0WhLzQo-b7imqHIo)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L23)):</sup>
Yeah, a proud screenshot it is! :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions, some commit checks failed.

---

<sup>**[src/pileup.js, line 79 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0bmhGfXQZOFXRo_z)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/src/pileup.js#L79)):</sup>
yeah, these changes are not really required for BioJS, but made the code cleaner IMHO. Will keep them as they are for the time being, but let me know if you prefer reverting these better.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by danvk** [comment]
Review status: 0 of 8 files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[examples/playground.html, line 18 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT1z7AVrJcRPQTXTvx)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/examples/playground.html#L18)):</sup>
Can you make this `window.yourDiv` to make it more explicit that you're creating a global var?

---

<sup>**[README.md, line 13 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2AkCPshpYp-Hl4Kn)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/README.md#L13)):</sup>
This isn't really true anymore, right? The node `http-server` will work as well. Maybe keep the old text and add a new section about running via BioJS sniper?

---

<sup>**[README.md, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0J9iRoja7M_9HK9s)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L19)):</sup>
Were you loading any data files (bigbed, 2bit or BAM) via the sniper server?

---

<sup>**[README.md, line 54 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2MBBockJsRMSB6P5)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/README.md#L54)):</sup>
Just curious--did you get this set up?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by danvk** [comment]
Review status: 0 of 8 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[examples/playground.js, line 12 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2ktNIjy1cs9EW6dA)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/examples/playground.js#L12)):</sup>
ddd

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by danvk** [comment]
Review status: 0 of 8 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[examples/playground.js, line 12 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2ktNIjy1cs9EW6dA)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/examples/playground.js#L12)):</sup>
oops, testing :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by danvk** [comment]
BTW, you don't need to hit the "publish immediately" button after responding to comments in Reviewable. The usual workflow is to reply to or acknowledge all the comments, then hit the big green "Publish" button on the top to publish them all in one go. That way you don't get a separate email for every single comment. (This is one of the wins of using Reviewable over GitHub for code reviews.)

---

Review status: 0 of 8 files reviewed, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 19 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0J9iRoja7M_9HK9s)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L19)):</sup>
I was wrong: looks like `sniper` uses `ecstatic` and it does not support range requests (tried testing by sending custom headers via curl). This means that sniper demos will fail if we try to serve data files as part of the demo, right?

Ah, bummer. 

---

<sup>**[README.md, line 54 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2MBBockJsRMSB6P5)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/README.md#L54)):</sup>
Unfortunately, no -- flow binary does not work on my crappy laptop so I wasn't able to get this running.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by danvk** [comment]
Looks good, feel free to:
1. Merge
2. Tag a new release (I can walk you through this)
3. Publish the new release on NPM (I assume you'll need some kind of permissions).

Thanks for making these changes!

---

Review status: 0 of 8 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 26 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrJ0J9iRoja7M_9HK9s)** ([raw file](https://github.com/hammerlab/pileup.js/blob/96055d938a97ea00568fa140854cbe0a585b9353/README.md#L26)):</sup>
Yeah, I guess you just have to use remote data if you're using sniper. Support for range requests is fairly unusual. I actually [built](https://github.com/danvk/RangeHTTPServer) a Python one before discovering that node's `http-server` supported them.

---

<sup>**[README.md, line 51 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/169#-JrT2MBBockJsRMSB6P5)** ([raw file](https://github.com/hammerlab/pileup.js/blob/20718cc930c6410a5c0864e5684258d958156d9f/README.md#L51)):</sup>
OK. I can help you debug if you like, it's pretty important for doing development with pileup!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Comment by armish** [comment]
Thanks for the peer review, Dan! I will do better next time ;)

---

Review status: 0 of 8 files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/169)

**Pull request merged**
