### PR TITLE
Add more documentation

### PR DESCRIPTION
**Pull request by danvk**
@armish this might have been helpful for you last summer! :)

@ihodes would also appreciate a once-over from you.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/402)

### CODE REVIEW

**Comment by armish** [comment]
:thumbsup: & :disappointed_relieved:  

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DESIGN.md, line 59 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/402#-K9cMlXruCaOSGLQUH_8:-K9cMlXruCaOSGLQUH_9:-521415518) ([raw file](https://github.com/hammerlab/pileup.js/blob/57ea8e331afc0597665c2e1e0ecc9f4db803a7fb/DESIGN.md#L59)):*
Maybe add a sentence about which one to use in which context?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/402#-:-K9cNUeRFeB4_hh6jUWN:-1831455046)*

**Comment by armish** [comment]
s/ :disappointed_relieved: / :disappointed: /g

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/402#-:-K9cOB57Ebvgddy4-Lnj:-1605299839)*

**Comment by danvk** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DESIGN.md, line 59 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/402#-K9cMlXruCaOSGLQUH_8:-K9cOw_cwfWAFerjBACp:-499146009) ([raw file](https://github.com/hammerlab/pileup.js/blob/57ea8e331afc0597665c2e1e0ecc9f4db803a7fb/DESIGN.md#L59)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/402)*

**Comment by armish** [comment]
:lgtm_strong: <- TIL ;)

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/402#-:-K9cQ2KVrmw5d7PdCxg8:-1729685613)*

**Pull request merged**
