### PR TITLE
Update react

### LINKED ISSUE #246: Drop the react-id hack
Once React 0.14 is out, it shouldn't be necessary. See https://github.com/facebook/react/pull/4747

This would involve deleting `react-shim.js` and updating `require('react-shim')`→`require('react')` everywhere.

### PR DESCRIPTION
**Pull request by danvk**
Fixes #246

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/314)

### CODE REVIEW

**Comment by danvk** [comment]
cc @ihodes 

Main changes with React 0.14 are:

- `ReactDOM` becomes its own library
- `refs` are now DOM nodes, not objects with a `getDOMNode` method.
- addons are split into their own libs

**Comment by armish** [comment]
nice refactoring! The code looks much cleaner without all those repetitive `getDOMNode` calls :)

:+1:


---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/main/GeneTrack.js, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/314#-K115wSOtIjpxKAw3G8Q)** ([raw file](https://github.com/hammerlab/pileup.js/blob/33ad9fa633586c5f64b5feae023efedd86f1874f/src/main/GeneTrack.js#L16)):</sup>
any reason as to why you split these definitions into two?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/314)

**Comment by danvk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/main/GeneTrack.js, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/314#-K115wSOtIjpxKAw3G8Q)** ([raw file](https://github.com/hammerlab/pileup.js/blob/33ad9fa633586c5f64b5feae023efedd86f1874f/src/main/GeneTrack.js#L16)):</sup>
It's third-party vs. first-party libraries. What do you think? Useful distinction?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/314)

**Comment by danvk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/main/GeneTrack.js, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/314#-K115wSOtIjpxKAw3G8Q)** ([raw file](https://github.com/hammerlab/pileup.js/blob/33ad9fa633586c5f64b5feae023efedd86f1874f/src/main/GeneTrack.js#L16)):</sup>
(this is kinda like the PEP8 style from Python)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/314)

**Comment by armish** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/main/GeneTrack.js, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/314#-K115wSOtIjpxKAw3G8Q)** ([raw file](https://github.com/hammerlab/pileup.js/blob/33ad9fa633586c5f64b5feae023efedd86f1874f/src/main/GeneTrack.js#L16)):</sup>
I think it is useful -- I like it!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/314)

**Pull request merged**
