### PR TITLE
Migrate PileupTrack from SVG→canvas

### PR DESCRIPTION
**Pull request by danvk**
See #255 

When I remove all tracks but a single `PileupTrack`, I see panning performance at ~700bp scale go from ~20fps→60fps. It's better than that, though. The SVG version sometimes goes down to around 6fps while panning, whereas the canvas version never drops below 30fps.

Remaining bits to implement:
- [x] Make mismatched base pairs the correct font/size
- [x] Make mismatches turn into blocks of color
- [x] Add back click handler support
- [x] Update the tests to understand canvas

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pileup.js/257)

### CODE REVIEW

**Comment by armish** [comment]
Reviewed 2 of 4 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/lint.sh, line 2 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr0Yeu3CVo_9KG2Jv0)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/scripts/lint.sh#L2)):</sup>
short-term or long-term disabling  for the checks?

---

<sup>**[src/main/data-canvas.js, line 142 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr1sS1k91y3Mw7h8sG)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/main/data-canvas.js#L142)):</sup>
never thought about this before, but are text styles/fonts going to cause us trouble? (e.g. tricky fonts that context doesn't know how to draw, etc.)

---

<sup>**[src/test/data-canvas-test.js, line 60 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr-iZiU2j9B1RK63Ho)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/test/data-canvas-test.js#L60)):</sup>
hmm, a little bit puzzled by this: do you have to know a click's coordinates before drawing an object to be able to capture the hits?

---

<sup>**[src/test/PileupTrack-test.js, line 9 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr0JKLiYeLIMFP1Wad)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/test/PileupTrack-test.js#L9)):</sup>
leftover?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Comment by danvk** [comment]
Addressed all comments & added fonts/changing to rects for mismatches. PTAL.

---

Review status: 14 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[scripts/lint.sh, line 0 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr0Yeu3CVo_9KG2Jv0)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/scripts/lint.sh#L0)):</sup>
Long-term. Unless we can find a good way to get this sort of thing to type-check with Flow. But the classes are all so dynamic. It's hard to see how Flow could possibly keep track of what we're doing here.

---

<sup>**[src/main/data-canvas.js, line 0 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr1sS1k91y3Mw7h8sG)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/main/data-canvas.js#L0)):</sup>
`CanvasRenderingContext2D` has a [`font`][1] property which can be set to any CSS font string. I've update this code to show a letter or rectangle as is appropriate for the scale. Check it out.

It would be nice if we could figure out what this font string should be using CSS, but I'd like to punt on that for a future PR.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font

---

<sup>**[src/test/data-canvas-test.js, line 0 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr-iZiU2j9B1RK63Ho)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/test/data-canvas-test.js#L0)):</sup>
Yep. It _feels_ inefficient, until you remember that clicks don't happen that often and that rendering a scene is really cheap if you don't actually have to render any pixels.

---

<sup>**[src/test/PileupTrack-test.js, line 9 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr0JKLiYeLIMFP1Wad)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/test/PileupTrack-test.js#L9)):</sup>
Yep, nice catch! Removed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Comment by danvk** [comment]
@ihodes would enjoy a review from you, too, since this is introducing a new abstraction.

**Comment by armish** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/test/data-canvas-test.js, line 60 \[r2\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-Jzr-iZiU2j9B1RK63Ho)** ([raw file](https://github.com/hammerlab/pileup.js/blob/81addeb6f0edc37b1e759f41075bdfa1ecde671d/src/test/data-canvas-test.js#L60)):</sup>
I see -- that does make sense then. Thanks a lot for explaining the rationale!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Comment by ihodes** [comment]
Yeah, this approach is pretty great. Nicely done.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/main/data-canvas.js, line 17 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-JzulxBf5QMSyDSce5ZH)** ([raw file](https://github.com/hammerlab/pileup.js/blob/42d242bd8b5d82cd4337303b25283e896086bc37/src/main/data-canvas.js#L17)):</sup>
FWIW I believe you can give an optional parameter a default value in the type signature, like `... onlyAccessors: ?boolean = false) {...`

---

<sup>**[src/main/data-canvas.js, line 25 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-JzvCyOdBuGiPqzJyohj)** ([raw file](https://github.com/hammerlab/pileup.js/blob/42d242bd8b5d82cd4337303b25283e896086bc37/src/main/data-canvas.js#L25)):</sup>
Just a note. No idea if this'll actually be a bottleneck, but in my deep-dive into JS JITs last year, I found that getters and setters in JS (at least then) could only be handled in the interpreter/could never get JITted. So this could potentially cause some serious slowness, depending. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Comment by danvk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/main/data-canvas.js, line 17 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-JzulxBf5QMSyDSce5ZH)** ([raw file](https://github.com/hammerlab/pileup.js/blob/42d242bd8b5d82cd4337303b25283e896086bc37/src/main/data-canvas.js#L17)):</sup>
Nice idea, but it looks like our transpiler doesn't support that yet:

```
function forward(obj        , target        , onlyAccessors           = false) {
Uncaught SyntaxError: Unexpected token =
```

---

<sup>**[src/main/data-canvas.js, line 25 \[r3\]](https://reviewable.io:443/reviews/hammerlab/pileup.js/257#-JzvCyOdBuGiPqzJyohj)** ([raw file](https://github.com/hammerlab/pileup.js/blob/42d242bd8b5d82cd4337303b25283e896086bc37/src/main/data-canvas.js#L25)):</sup>
I haven't noticed any slowdown from using data-canvas, but I'll keep that in mind. I think the cost of throwing lots of pixels on the canvas dwarfs the JavaScript costs.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Comment by danvk** [comment]
Thanks! I'll go ahead and merge.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pileup.js/257)

**Pull request merged**
